server:
  port: 8000
---
spring:
  cloud:
    gateway:
      default-filters: #CORS 설정
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://192.168.0.100:8000"
              - "http://192.168.0.100:8080"
              - "http://localhost:8080"
              - "http://localhost:8000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
---
spring:
  cloud:
    gateway:
      default-filters: #gateway 항목정의.
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: login
          uri: http://10.0.1.168:9000/
          #uri: http://localhost:9000/
          predicates:
            - Path=/authen/** #- Path=/authen/**, /login/**
          filters:
            - name: LoginFilter
              args:
                baseMessage: Spring Cloud Gateway LoginFilter
                preLogger: true
                postLogger: true
        - id: cms
          #uri: http://192.168.0.100:9001/
          uri: http://10.0.1.168:9001/
          #uri: http://localhost:9001/
          predicates:
            - Path=/cms/** #- Path=/authen/**, /login/**
          filters:
            - name: CMSFilter
              args:
                baseMessage: Spring Cloud Gateway CMSFilter
                preLogger: true
                postLogger: true
        - id: autho
          #uri: http://localhost:8000/
          uri: http://10.0.1.168:8000/
          predicates:
            - Path=/autho/**


        #- id: Autho
        #  uri: http://localhost:8000/
        #  predicates:
        #   - Path=/autho/**
        #  filters:
        #    - name: AuthFilter
        #      args:
        #        baseMessage: Spring Cloud Gateway AuthoFilter
        #        preLogger: true
        #        postLogger: true

